### ISSUE TITLE
Feature request:  Display collapse toggle on hover of the line number side bar.

### ISSUE THREAD

**Issue by cliffordfajardo** [melke/markdown-folder#14]
Currently built into Atom core is the ability to collapse code blocks via `cmd - option- {` for collapse & `cmd - option- }` for uncollapse or by hovering over the left sidebar containing the editor's line number, which displays the upside down triangle toggle. 

If you could also have the ability to hover over the editors line numbers to display the collapse-code toggle for your package that would be great!

![screen shot 2016-03-09 at 9 47 05 am](https://cloud.githubusercontent.com/assets/6743796/13644759/4a3da218-e5dc-11e5-8e95-acd0addcdd0d.png)

**Comment by melke** [comment]
Hi, thanks for your suggestion! I'm afraid, though, that it's not possible to fold markdown using the normal Atom API methods, since the lang package does not consider markdown sections being code blocks. So, the whole markdown-folder package is really just an ugly hack searching for heading prefixes and folding each line in that section individually. That's also the reason why the normal commands for folding can't be used in this package. Normal unfolding works though.
