### ISSUE TITLE
Toggle under a heading

### ISSUE THREAD

**Issue by brettz9** [melke/markdown-folder#15]
Great add-on!

I was just wondering whether it would be possible for you to support 'markdown-folder:toggle' within a section, so that when expanded, opting to toggle would collapse and move the cursor up to the heading, while toggling again would expand the heading (and ideally put the cursor back where you had been within the section)...

Thanks a lot!

**Comment by melke** [comment]
Hi, thanks for the feedback. This would be a nice feature, although it would be quite hairy to implement. Due to underlying limitations, the markdown-folder package needs to achieve what it does in a very hacky and fragile way, so frankly, I'm very hesitant to add more complexity. If you find a safe way of implementing the feature though, please send a PR and I will have a look at it.  Meanwhile, I'll close this.

**Comment by brettz9** [comment]
Ok, thanks!
